# general settings
name: ep420_track1_c_grad_lap_sam_vgg19_l1
model_type: ESRGANModel_C_Grad
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

use_USM: false
need_HR: true
weighted_loss: false
low_f_loss: true
low_f_loss_weight: 1  # pixel_loss_weight * low_f_loss_weight

FS:
  norm: true
  type: gau
  kernel_size: 9

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /home/tangjingzhu/Works/Dataset/NITRE2020/Track1/corrupted_train_y
    dataroot_lq: /home/tangjingzhu/Works/Real-SR/_Experiments/DSN_ADL/results/mile250_track1_resnet_uncertainty_unet_kl_gau_bic_per_vgg19_l1_ep420/down_results/ep_0001
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X4_sub.lmdb
    filename_tmpl: '{}'
    color: ~
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 6
#    dataset_enlarge_ratio: 100
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Canon
    type: PairedImageDataset
    dataroot_gt: /home/tangjingzhu/Works/Dataset/NITRE2020/Track1/corrupted_valid_y
    dataroot_lq: /home/tangjingzhu/Works/Dataset/NITRE2020/Track1/corrupted_valid_x
    color: ~
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet_two_vgg19
  checkpoint_var: /home/tangjingzhu/Works/Real-SR/_Experiments/DSN_ADL/experiments/mile250_track1_resnet_uncertainty_unet_kl_gau_bic_per_vgg19_l1/models/training_down_0420.pth
  checkpoint_U: /home/tangjingzhu/Works/Real-SR/_Experiments/SRN_ESRGAN/pretrained_model/RRDB_PSNR_x4.pth
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  # weighted_loss: false

network_d:
  type: UNetDiscriminatorSN
  num_in_ch: 3
  num_feat: 64

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0
  optim_g:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      # before relu
      'conv5_4': 1
    vgg_type: vgg19
    use_input_norm: true
    perceptual_weight: 1.0
    style_weight: 0
    range_norm: false
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 1e-1

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 5e2
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
    lpips:
      type: calculate_lpips
      crop_border: 4

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
